In [46]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [47]:
## your code

# Вектор-строка двоек
twos = 2*np.ones(20)

# Вектор-строка [1, 2, ..., 20]
rang_e = np.arange(1, 21)


#Поэлементные операции
result = ( twos ) ** rang_e / rang_e

print(result)

[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04 5.24288000e+04]


**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [48]:
## your code

# Вектор-строка [0.1]*5
ones = 0.1*np.ones(6)

# Вектор-строка [0.2]*5
twos = 0.2*np.ones(6)

# Индекс
rang_e = np.arange(0, 6, 1)

# Вектор первых сомножителей
res_ones = ones ** (rang_e * 3)

# Вектор вторых сомножителей
res_twos = twos ** (rang_e * 4)

# Скалярное произведение
result = res_ones @ res_twos

print(result)

1.00000160000256


**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [49]:
## your code

# Нулевая матрица
zeros = np.zeros((8, 8))

# Матрица с суммой индексов по строкам и столбцам
rang_e = np.arange(1, 9) + ( np.arange(1, 9) ).reshape(8, 1)

# Логическая маска
MASk = rang_e % 2 == 0

zeros[MASk] = 1

print(zeros)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [50]:
X = np.random.random((5, 2))

## your code

# Абсциссы 
x = X[:, 0]

# Ординаты 
y = X[:, 1]

# Модули
r = np.sqrt(x**2 + y**2)

# Углы
alpha = np.arctan(y / x) 

print(r, alpha)

[0.78337991 1.34756247 0.68828367 0.66802118 1.13621228] [0.30835855 0.75647673 0.79625319 0.33672243 0.77585872]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [51]:
X = np.random.random((10, 10))

## your code
res = np.argmax(X) // (X.shape)[0], np.argmax(X) % (X.shape)[0]

print(res)

print(X[res])

(8, 0)
0.9970368227321023


**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [52]:
X = np.random.random((10, 2))

y = np.random.random((1, 2))

## your code

# Первая координата
x_1 = X[:, 0]

# Вторая координата
x_2 = X[:, 1]

# Индекс наименьшего евклидова расстояния
index = np.argmin( (x_1 - y[0, 0])**2 + (x_2 - y[0, 1])**2 )

res = X[index]

print(y)
print(res)

[[0.8339594  0.84056353]]
[0.99378332 0.69566517]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [53]:
## your code

# Число точек разбиения
x = np.linspace(-3, 3, 51)

# Первый отрезок (x<0)
x_1 = x[x<0]

# Второй отрезок (x>=0 and x <=2)
x_2 = (x[x>=0])[ (x[x>=0])<=2 ]

# Третий отрезок (x > 2)
x_3 = x[x>2]

# Значения на первом отрезке
res_1 = x_1**2 + 2*x_1 + 6

# Значения на втором отрезке
res_2 = x_2 + 6

# Значения на третьем отрезке
res_3 = x_3**2 + 4*x_3 - 4

# Конкатенация
res = np.hstack((res_1, res_2))
res = np.hstack((res, res_3))

print(res)

[ 9.      8.5344  8.0976  7.6896  7.3104  6.96    6.6384  6.3456  6.0816
  5.8464  5.64    5.4624  5.3136  5.1936  5.1024  5.04    5.0064  5.0016
  5.0256  5.0784  5.16    5.2704  5.4096  5.5776  5.7744  6.      6.12
  6.24    6.36    6.48    6.6     6.72    6.84    6.96    7.08    7.2
  7.32    7.44    7.56    7.68    7.8     7.92    8.3216  9.3056 10.3184
 11.36   12.4304 13.5296 14.6576 15.8144 17.    ]


**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [54]:
X = np.random.random((10, 10))

## your code
res = X - (np.mean(X, axis = 1) ).reshape( (X.shape)[0], 1)

print(res)
print(np.mean(res, axis = 1))

[[ 0.03101673  0.24241535 -0.12504548 -0.07720219  0.26791726 -0.03710217
   0.09458134 -0.00191249  0.11519531 -0.50986365]
 [-0.34620199  0.42924378  0.27970817 -0.17279056 -0.18217534  0.10813624
   0.21478888 -0.39855431  0.03907839  0.02876674]
 [-0.26477534  0.10199856  0.12186091  0.49524869  0.1570881  -0.23106321
  -0.20514082 -0.36659271 -0.18274476  0.37412058]
 [-0.20207886 -0.07301649 -0.0804074   0.23061031  0.2198664   0.0454639
  -0.12615709  0.02956877 -0.09643387  0.05258433]
 [-0.40295544  0.0062106   0.40866737 -0.01188004  0.03983924  0.16667378
  -0.26859021  0.20341825 -0.47111617  0.32973264]
 [ 0.02303275  0.04340993 -0.40288648  0.21794088 -0.2341665  -0.33382847
   0.34652242  0.23628308  0.13051629 -0.0268239 ]
 [-0.19210947 -0.40436225  0.47979634 -0.40291961  0.49943344  0.29999034
  -0.35691216  0.03653119  0.25649268 -0.21594051]
 [-0.09184102 -0.19694461  0.46422921  0.112046   -0.16137689 -0.04216842
   0.03265582 -0.18630123  0.44637618 -0.37667504]
 

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [55]:
X = np.random.normal(loc=5, scale=2., size=1000)

## your code
mean = np.sum(X)/1000
disp = np.sqrt(np.sum( ( X - mean )**2 )/1000)

print(mean, disp)

5.053585927173205 1.9182218868796803


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [56]:
## your code

# Вектор [0, 1, 2, 3, 4]
a = (np.arange(0, 5)).reshape(1, 5)

# Получаем матрицу путём сложения двух векторов
res = a + a.reshape(5, -1)

# Берём остаток от деления на 5
res = res % 5

print(res)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [57]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 1, 4, 4, 0]

In [58]:
## your code
# Алгоритм:
# 1) Суммирует все элементы
# 2) c раз совершает:
#    a) Умножает сумму на случайный, равномерно распределённый коэффициент из [0, 1)
#    б) Вычислляет, сумма скольки первых чисел в массиве меньше умноженной на коэфициент общей суммы

# Входные данные
x = [50, 3, 1, 7, 20]

In [61]:
def my_sample(x, c):
    assert len(x) > 0
    
    #Сумма всех элементов
    s = np.sum(x)
    
    # Получаем значения для сэмплирования
    vals = s*np.random.random((c, 1))
    print('vals: ', vals.T)
    
    # Получаем последовательные суммы элементов [1,..., i] для i из [1, len(x)] домножением
    # нижнетреугольную матрицу
    sums = np.dot(np.tri(len(x)), np.array(x).T )
    print('sums: ', sums)
    
    res = np.argmax( (sums - vals) > 0, axis = 1 )
    
    print(res)

In [62]:
my_sample([50, 3, 1, 7, 20], 5)

vals:  [[55.92176787 68.84446757 39.37446241 32.55134546 46.22100214]]
sums:  [50. 53. 54. 61. 81.]
[3 4 0 0 0]
